defaultBaseImage: gcr.io/distroless/static-debian11:latest
builds:
- env:
  - CGO_ENABLED=0
  flags:
  - -v
  ldflags:
  - -s
  - -w
  - -X github.com/nholuongut/external-dns/pkg/apis/externaldns.Version={{.Env.VERSION}}
